version: "2"
services:
  app:
    build: .
    links:
      - db
    depends-on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    command: ["sleep", "60"]